name: AWS CodeBuild CI

# 2. Define triggers for the workflow.
# 'push' runs the workflow on pushes to the main branch.
# 'pull_request' runs it on pull requests targeting the main branch.
# 'workflow_dispatch' allows you to run it manually from the Actions tab.
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  my-build-job:
    name: Build on AWS CodeBuild
    runs-on: codebuild-github-actions-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v3
      - name: Say Hello
        run: |
          set -e
          set -x
          echo "Hello from a CodeBuild runner!"
          env
          ip a
          uname -a
          free -m
          curl api.ipify.org
          docker version
