on:
  workflow_dispatch: []

jobs:
  my-build-job:
    name: Build on AWS CodeBuild
    runs-on: codebuild-github-actions-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v3
      - name: Say Hello
        run: echo "Hello from a CodeBuild runner!"
